server:
  port: 10086
spring:
  application:
    name: ly-registry
  freemarker:
    prefer-file-system-access: false
eureka:
  client:
    service-url:
      defaultZone: http://192.168.48.1:10086/eureka/
    fetch-registry: false
    register-with-eureka: false