server:
  port: 10086
spring:
  application:
    name: ly-registry
  freemarker:
    prefer-file-system-access: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086
    fetch-registry: false
    register-with-eureka: false